### ISSUE TITLE
broken deps - tools have moved

### ISSUE THREAD

**Issue by rhamnett** [CalebEverett/metaplex-cli#4]
FYI - https://github.com/metaplex-foundation/metaplex-program-library

Thanks

**Comment by CalebEverett** [comment]
deps in master have been updated

**Comment by CalebEverett** [comment]
I moved it out into its own crate https://github.com/CalebEverett/arloader

**Comment by CalebEverett** [comment]
The original goal of this repo was to be a turn key way to create NFTs on Solana, but getting files uploaded to Arweave turned out to be non-trivial and @samuelvanderwaal had developed [metaboss](https://github.com/samuelvanderwaal/metaboss) and didn't want to duplicate his fine efforts.

Happy to help with usage or answer any questions.
